name: payment_pdf_parse
description: Parses payment batch PDF files
version: 0.0.1
author: Todd Mannherz <todd.mannherz@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  archive:
  args:
  crypto:
  http:
  meta:
  path:
  shelf_exception_handler:
  shelf_route:
